version: "3"
services:
  app:
    build: .
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
networks:
  proxy:
    external: true
