const routes = {
  home: "/",
  aboutUs: "/about-us",
  abstract: "/abstract",
  checkEmail: "/check-email",
  education: "/education",
  FAQs: "/FAQs",
  forgetPassword: "/forget-password",
  privacyPolicy: "/privacy-policy",
  profile: "/profile",
  resetPasswordConfirmation: "/reset-password-confirmation",
  resetPassword: "/reset-password",
  scriptWriting: "/script-writing",
  signin: "/signin",
  signup: "/signup",
  termsAndCondition: "/terms-and-conditions",
  verifyEmail: "/verify-email",
  blog: "/blog",
  iDraft: "/iDraft",
  iDraftTermsAndConditions: "/iDraft/terms-and-conditions",
  marketplace: "/marketplace",
  marketPlaceSubscriptionSuccessful: "/marketplace/subscription-successful",
  marketPlaceSubscription: "/marketplace/subscription",
  listingsDashboard: "/dashboard/listings",
  projectsDashboard: "/dashboard/projects",
  reviewerDashboard: "/dashboard/reviewer",
  previewDashboard: "/dashboard/reviewer/preview",
  reviewsDashboard: "/dashboard/reviews",
  reviewsPaymentSuccessful: "/dashboard/reviews/payment-successful",
  reviewsPlans: "/dashboard/reviews/plans",
  reviewsSummary: "/dashboard/reviews/summary",
  scriptsDashboard: "/dashboard/scripts",
  withdrawWallet: "/wallet/withdraw",
  cryptoWithdrawWallet: "/wallet/crypto-withdraw",
  helpWallet: "/wallet/help",
  transactionHistoryWallet: "/wallet/transaction-history",
  withdrawSuccessfulWallet: "/wallet/withdraw-successful",
  depositWallet: "/wallet/deposit",
};

export default routes;
