export const genreList = [
  { genre: "Action" },
  { genre: "Comedy" },
  { genre: "Crime" },
  { genre: "Drama" },
  { genre: "Fantasy" },
  { genre: "Horror" },
  { genre: "Mystery" },
  { genre: "Romance" },
  { genre: "Thriller" },
  { genre: "Adventure" },
  { genre: "Experimental" },
  { genre: "Sci-fi" },
  { genre: "Gangster" },
  { genre: "Musical" },
  { genre: "Competition" },
  { genre: "Biographical" },
  { genre: "Historical" },
];

export const storyTopics = [
  "Abduction",
  "Adultery",
  "Adventure",
  "Ambition",
  "Anecdote",
  "Apologue",
  "Ascension & Descension",
  "Astral",
  "Bad influence",
  "Bedtime story",
  "Captivity",
  "Chivalric romance",
  "Coming of age",
  "Competition",
  "Conflict with a God",
  "Creation myth",
  "Crimes for vengeance",
  "Crimes of passion",
  "Crimes of war",
  "Cruelty of misfortune",
  "Daring Enterprise",
  "Deliverance",
  "Disaster",
  "Discovery of treasure",
  "Discovery of culture",
  "Dishonour of a loved me",
  "Drugs",
  "Enmity of Kinsmen",
  "Enemy Loved",
  "Erroneous judgment",
  "Etiological myth",
  "Escape",
  "Fable",
  "Factoid",
  "Fairy tale",
  "Falling Prey",
  "Family",
  "Farce",
  "Fatal imprudence",
  "Fish-Out-Of-Water",
  "Folklore",
  "Folkloristics",
  "Forbidden Love",
  "Friendship Love",
  "Ghost",
  "Grief",
  "Honour Killing",
  "Invention",
  "Involuntary Crimes of Love(Incest)",
  "Jujuism",
  "Joke",
  "Legend",
  "Loss of Loved Ones",
  "Love",
  "Madness",
  "Mental health",
  "Metamorphosis",
  "Mistaken Jealousy",
  "Murder",
  "Myths",
  "Necessity Invention",
  "Obstacles to Love",
  "Obtaining",
  "Oral tradition",
  "Parable",
  "Parenthood",
  "Political myth",
  "Popular belief",
  "Popular misconception",
  "Pursuit",
  "Quest",
  "Recovery of a Lost One",
  "Religion",
  "Remorse",
  "Rescue",
  "Revenge",
  "Revolt",
  "Riddle",
  "Rivalry",
  "Rivalry of Kinsman",
  "Rivalry of Superior and Inferior",
  "Sacrifice",
  "Satire",
  "Sacrifice for Passion",
  "Self-Sacrifice for an Ideal",
  "Self-Sacrifice for Kindred",
  "Separation",
  "Sex",
  "Short story",
  "Sibling Rivalry",
  "Supplication",
  "Tales by Moonlight",
  "Tall tales",
  "Technology",
  "Temptation",
  "Transformation",
  "Underdog",
  "Urban Legend",
  "Wretched Excess",
  "Youth Exuberance",
];
